token:
  expiration_time: 86400000
  secret: "{cipher}AYDOIY48B93DdVtjgt0137qKbGNZ/hYEkE9hkjVdAy1E7lU10oVOTikUj3uPqSew5IvbvvxUvLrSiHzpD0tINjWczGdqRmRWwyOWzHActXUkzTgyH063EYB4V+Mbl2+uNkuLCpABs3dhJFGa8sBaxEAzXbW7kOXN077YZw31yeNYQ3VGFkfQVqxuUIi4i2/bPQi661PLNfrD+wShAVNPxp35YScpRDVfD6sWN//IQgkKqSXhUTgahMIUGnyUaepuOcffExCuj7Dp5W7IXE7qQhtVsm+SiZuCkxvPmR7rC99KIWN5QwyZnhrYnG67WwIPe0eR+GGanZv5zVpu3fh2Ze56j6wvnGiXt1JVNpERRMA9kYKas6Kk2F3fj0O6SKoS/7cpcnxWIPoe++xYPaEO+T8qSq9F15WjGs9zWelwcdSffwayxszajfxT5cb84yq2M44CLvgsXMBgYxnU/RTjj0uJsLb6Hk8q5TEHteTZSXnz4yT/Ljgd/SPrQJPcUz+iSaAmYuUn+E+nYR9gayy/gYdJzprJMKWQO8DjWDY+ujmGdoZFHK8fqEoxQ0LouEtKxLUesYK+XuKCIbn10JhEmVCa"

gateway:
  ip: 172.30.1.100
